apps:
  - name: aiworkspace.60wattsofclarity.com
    log_date_format: "YYYY-MM-DD HH:mm:ss Z"
    cwd: /home/60wattsofclarity.com/aiworkspace.60wattsofclarity.com/
    script: "npm"
    args: "run start"
    interpreter: "/usr/bin/node"
    env:
      NODE_ENV: "production"
      PORT: 3061
